// oxlint-disable max-lines

export interface Book {
    title_en: string;
    title_fi: string;
    author: string;
    published: number | '-';
    read: boolean;
}

export const BOOKS: Book[] = [
    {
        author: 'Charles Dickens',
        published: 1837,
        read: true,
        title_en: "Oliver Twist; or, The Parish Boy's Progress",
        title_fi: 'Oliver Twist',
    },
    {
        author: 'Victor Hugo',
        published: 1862,
        read: true,
        title_en: 'Les Misérables',
        title_fi: 'Kurjat',
    },
    {
        author: 'Daniel Defoe',
        published: 1719,
        read: true,
        title_en: 'Robinson Crusoe',
        title_fi: 'Robinson Crusoe',
    },
    {
        author: '	Fyodor Dostoevsky',
        published: 1880,
        read: true,
        title_en: 'The Brothers Karamazov',
        title_fi: 'Karamazovin veljekset',
    },
    {
        author: 'Fyodor Dostoevsky',
        published: 1866,
        read: true,
        title_en: 'Crime and Punishment',
        title_fi: 'Rikos ja rangaistus',
    },
    {
        author: 'Mihail Bulgakov',
        published: 1926,
        read: true,
        title_en: 'The Master and Margarita',
        title_fi: 'Saatana saapuu Moskovaan',
    },
    {
        author: 'Leo Tolstoy',
        published: 1869,
        read: true,
        title_en: 'War and Peace',
        title_fi: 'Sota ja rauha',
    },
    {
        author: 'Walter Isaacson',
        published: 2011,
        read: true,
        title_en: 'Steve Jobs',
        title_fi: 'Steve Jobs',
    },
    { author: 'George Orwell', published: 1949, read: true, title_en: '1984', title_fi: '1984' },
    {
        author: 'yval Noah Harari',
        published: 2014,
        read: true,
        title_en: 'Sapiens: A Brief History of Humankind',
        title_fi: 'Sapiens: Ihmisen lyhyt historia',
    },
    {
        author: 'William Golding',
        published: 1954,
        read: true,
        title_en: 'Lord of the Flies',
        title_fi: 'Kärpästen herra',
    },
    {
        author: 'Donna Tartt',
        published: 1992,
        read: true,
        title_en: 'The Secret History',
        title_fi: 'Jumalat juhlivat öisin',
    },
    {
        author: 'J.R.R. Tolkien',
        published: 1954,
        read: true,
        title_en: 'The Lord of the Rings',
        title_fi: 'Taru sormusten herrasta',
    },
    {
        author: 'J.K. Rowling',
        published: 1997,
        read: true,
        title_en: 'Harry Potter',
        title_fi: 'Harry Potter',
    },
    {
        author: 'C.S. Lewis',
        published: 1950,
        read: true,
        title_en: 'The Chronicles of Narnia',
        title_fi: 'Narnian tarinat',
    },
    {
        author: 'J.D. Salinger',
        published: 1951,
        read: true,
        title_en: 'The Catcher in the Rye',
        title_fi: 'Sieppari ruispellossa',
    },
    {
        author: 'Anne Frank',
        published: 1947,
        read: true,
        title_en: 'The Diary of a Young Girl',
        title_fi: 'Nuoren tytön päiväkirja',
    },
    {
        author: 'Bram Stoker',
        published: 1897,
        read: true,
        title_en: 'Dracula',
        title_fi: 'Dracula',
    },
    {
        author: 'Sir Arthur Conan Doyle',
        published: 1892,
        read: true,
        title_en: 'The Hound of the Baskervilles',
        title_fi: 'Baskervillen koira',
    },
    {
        author: 'Alexandre Dumas',
        published: 1844,
        read: true,
        title_en: 'The Three Musketeers',
        title_fi: 'Kolme muskettisoturia',
    },
    {
        author: 'Alexandre Dumas',
        published: 1844,
        read: true,
        title_en: 'The Count of Monte Cristo',
        title_fi: 'Monte-Criston kreivi',
    },
    {
        author: 'Richard Adams',
        published: 1972,
        read: true,
        title_en: 'Watership Down',
        title_fi: 'Ruohometsän kansa',
    },
    {
        author: 'Agatha Christie',
        published: 1939,
        read: true,
        title_en: 'And Then There Were None',
        title_fi: 'Eikä yksikään pelastunut',
    },
    {
        author: 'Mary Shelley',
        published: 1818,
        read: true,
        title_en: 'Frankenstein; or, the Modern Prometheus',
        title_fi: 'Frankenstein. Uusi Prometheus',
    },
    {
        author: 'Robert Louis Stevenson',
        published: 1886,
        read: true,
        title_en: 'Strange Case of Dr Jekyll and Mr Hyde',
        title_fi: 'Tohtori Jekyll ja Mr. Hyde',
    },
    {
        author: 'Franz Kafka',
        published: 1925,
        read: true,
        title_en: 'The Trial',
        title_fi: 'Oikeusjuttu',
    },
    {
        author: 'Väinö Linna',
        published: 1954,
        read: true,
        title_en: 'The Unknown Soldier',
        title_fi: 'Tuntematon sotilas',
    },
    {
        author: 'Paulo Coelho',
        published: 1988,
        read: true,
        title_en: 'The Alchemist',
        title_fi: 'Alkemisti',
    },
    { author: 'Frank Herbert', published: 1965, read: true, title_en: 'Dune', title_fi: 'Dyyni' },
    {
        author: 'Oscar Wilde',
        published: 1890,
        read: true,
        title_en: 'The Picture of Dorian Gray',
        title_fi: 'Dorian Grayn muotokuva',
    },
    {
        author: 'Markus Zusak',
        published: 2005,
        read: true,
        title_en: 'The Book Thief',
        title_fi: 'Kirjavaras',
    },
    {
        author: 'John Irving',
        published: 1978,
        read: true,
        title_en: 'The World According to Garp',
        title_fi: 'Garpin maailma',
    },
    {
        author: 'Ken Kesey',
        published: 1962,
        read: true,
        title_en: "One Flew Over the Cuckoo's Nest",
        title_fi: 'Yksi lensi yli käenpesän',
    },
    {
        author: 'Aleksis Kivi',
        published: 1870,
        read: true,
        title_en: 'Seven Brothers',
        title_fi: 'Seitsemän veljestä',
    },
    {
        author: 'Kari Hotakainen',
        published: 2002,
        read: true,
        title_en: 'Juoksuhaudantie',
        title_fi: 'Juoksuhaudantie',
    },
    {
        author: 'Harper Lee',
        published: 1960,
        read: true,
        title_en: 'To Kill a Mockingbird',
        title_fi: 'Kuin surmaisi satakielen',
    },
    {
        author: 'Uzodinma Iweala',
        published: 2005,
        read: true,
        title_en: 'Beasts of No Nation',
        title_fi: 'Ei kenenkään lapset',
    },
    {
        author: 'Fabio Geda',
        published: 2010,
        read: true,
        title_en: 'In the Sea There are Crocodiles',
        title_fi: 'Krokotiilimeri',
    },
    {
        author: 'Leo Tolstoy',
        published: 1875,
        read: true,
        title_en: 'Anna Karenina',
        title_fi: 'Anna Karenina',
    },
    {
        author: 'John Boyne',
        published: 2006,
        read: true,
        title_en: 'The Boy in the Striped Pyjamas',
        title_fi: 'Poika raidallisessa pyjamassa',
    },
    {
        author: 'F. Scott Fitzgerald',
        published: 1925,
        read: true,
        title_en: 'The Great Gatsby',
        title_fi: 'Kultahattu',
    },
    {
        author: 'George Orwell',
        published: 1945,
        read: true,
        title_en: 'Animal Farm',
        title_fi: 'Eläinten vallankumous',
    },
    {
        author: 'Fyodor Dostoevsky',
        published: 1860,
        read: true,
        title_en: 'The House of the Dead',
        title_fi: 'Kirjoituksia kellarista',
    },
    {
        author: 'Franz Kafka',
        published: '-',
        read: true,
        title_en: '(Kafka Novels)',
        title_fi: '(Kafkan Novellit)',
    },
    {
        author: 'Boris Akunin',
        published: 1998,
        read: true,
        title_en: 'The Winter Queen',
        title_fi: 'Asaselin salaliitto',
    },
    {
        author: 'Fyodor Dostoevsky',
        published: 1868,
        read: true,
        title_en: 'The Idiot',
        title_fi: 'Idiootti',
    },
    { author: '-', published: '-', read: true, title_en: 'The Bible', title_fi: 'Raamattu' },
    {
        author: 'John Steinbeck',
        published: 1939,
        read: true,
        title_en: 'The Grapes of Wrath',
        title_fi: 'Vihan hedelmät',
    },
    {
        author: 'Jane Austen',
        published: 1813,
        read: true,
        title_en: 'Pride and Prejudice',
        title_fi: 'Ylpeys ja ennakkoluuko',
    },
    {
        author: 'Guy de Maupassant',
        published: 1885,
        read: true,
        title_en: 'Bel-Ami',
        title_fi: 'Bel-Ami',
    },
    {
        author: 'Leo Tolstoy',
        published: 1852,
        read: true,
        title_en: 'The Cossacks',
        title_fi: 'Kasakat',
    },
    {
        author: 'Charles Dickens',
        published: 1850,
        read: true,
        title_en: 'David Copperfield',
        title_fi: 'David Copperfield',
    },
    {
        author: 'John Steinbeck',
        published: 1937,
        read: true,
        title_en: 'Of Mice and Men',
        title_fi: 'Hiiriä ja ihmisiä',
    },
    {
        author: 'Władysław Szpilman',
        published: 1946,
        read: true,
        title_en: 'The Death of a City',
        title_fi: 'Pianisti',
    },
    {
        author: 'Fyodor Dostoevsky',
        published: 1872,
        read: true,
        title_en: 'Demons',
        title_fi: 'Riivaajat',
    },
    {
        author: 'Mika Waltari',
        published: 1945,
        read: true,
        title_en: 'The Egyptian',
        title_fi: 'Sinuhe egyptiläinen',
    },
    {
        author: 'Franz Kafka',
        published: 1927,
        read: true,
        title_en: 'The Man Who Disappeared (Amerika)',
        title_fi: 'Mies joka katosi (Amerikka)',
    },
    {
        author: 'Jane Austen',
        published: 1818,
        read: true,
        title_en: 'Persuasion',
        title_fi: 'Viisasteleva sydän',
    },
    {
        author: 'Miguel de Cervantes',
        published: 1605,
        read: true,
        title_en: 'The Ingenious Gentleman Don Quixote of La Mancha',
        title_fi: 'Neuvokas ritari don Quijote Manchalainen',
    },
    {
        author: 'Astrid Lindgren',
        published: 1981,
        read: true,
        title_en: "Ronja, the Robber's Daughter",
        title_fi: 'Ronja, ryövärintytär',
    },
    {
        author: 'Astrid Lindgren',
        published: 1973,
        read: true,
        title_en: 'The Brothers Lionheart',
        title_fi: 'Veljeni, Leijonamieli',
    },
    {
        author: 'Charles Dickens',
        published: 1839,
        read: true,
        title_en: 'The Life and Adventures of Nicholas Nickleby',
        title_fi: 'Nicholas Nicklebyn elämä ja seikkailut',
    },
    {
        author: 'Gabriel García Márquezin',
        published: 1967,
        read: true,
        title_en: 'One Hundred Years of Solitude',
        title_fi: 'Sadan vuoden yksinäisyys',
    },

    {
        author: 'George Eliot (Mary Ann Evans)',
        published: 1871,
        read: false,
        title_en: 'Middlemarch, A Study of Provincial Life',
        title_fi: 'Middlemarch',
    },
    {
        author: 'Emily Brontë',
        published: 1847,
        read: false,
        title_en: 'Wuthering Heights',
        title_fi: 'Humiseva harju',
    },
    {
        author: 'Albert Camus',
        published: 1942,
        read: false,
        title_en: 'The Stranger',
        title_fi: 'Sivullinen',
    },
    {
        author: 'Aldous Huxley',
        published: 1932,
        read: false,
        title_en: 'Brave New World',
        title_fi: 'Uljas uusi maailma',
    },
    {
        author: 'Jane Austen',
        published: 1811,
        read: false,
        title_en: 'Sense and Sensibility',
        title_fi: 'Järki ja tunteet',
    },
    {
        author: 'Aleksandr Puškin',
        published: 1836,
        read: false,
        title_en: "The Captain's Daughter",
        title_fi: 'Kapteenin tytär',
    },
    {
        author: 'Mihail Lermontov',
        published: 1840,
        read: false,
        title_en: 'A Hero of Our Time',
        title_fi: 'Aikamme sankari',
    },
    {
        author: 'Ivan Turgenev',
        published: 1862,
        read: false,
        title_en: 'Fathers and Sons',
        title_fi: 'Isät ja pojat',
    },
    {
        author: 'Louisa May Alcott',
        published: 1868,
        read: false,
        title_en: 'Little Women',
        title_fi: 'Pikku naisia',
    },
    {
        author: 'Charles Dickens',
        published: 1852,
        read: false,
        title_en: 'Bleak House',
        title_fi: 'Kolea talo',
    },
    {
        author: 'Charles Dickens',
        published: 1859,
        read: false,
        title_en: 'A Tale of Two Cities',
        title_fi: 'Kaksi kaupunkia',
    },
    {
        author: 'Charles Dickens',
        published: 1860,
        read: false,
        title_en: 'Great Expectations',
        title_fi: 'Loistava tulevaisuus',
    },
    {
        author: 'Charles Dickens',
        published: 1864,
        read: false,
        title_en: 'Our Mutual Friend',
        title_fi: '-',
    },
];
