export interface Book {
    title_en: string;
    title_fi: string;
    author: string;
    published: number;
    read: boolean;
}

export const BOOKS: Book[] = [
    { author: '', published: 0, read: true, title_en: 'oliver twist', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'kurjat', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'robinson crusoe', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'karamazovin veljekset', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'rikos ja rangaistus', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'saatana saapuu moskovaan', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'sota ja rauha', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'steve jobs elämäkerta', title_fi: '' },
    { author: '', published: 0, read: true, title_en: '1984', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'ihmisen lyhyt historia', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'kärpästen herra', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'jumalat juhlivat öisin', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'taru sormusten herrasta', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'harry potter', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'narnia', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'sieppari ruispellossa', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'anne frank', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'dracula', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'baskervillen koira', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'kolme muskettisoturia', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'monte criston kreivi', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'ruohometsän kansa', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'eikä yksikään pelastunut', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'frankenstein', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'tri jekyll ja mr hyde', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'oikeusjuttu', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'tuntematon sotilas', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'alkemisti', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'dyyni', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'dorian grayn muotokuva', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'kirjavaras', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'garpin maailma', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'yksi lensi yli käenpesän', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'seitsemän veljestä', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'juoksuhaudantie', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'kuin surmaisi satakielen', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'ei kenenkään lapset', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'krokotiilimeri', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'anna karenina', title_fi: '' },
    {
        author: '',
        published: 0,
        read: true,
        title_en: 'poika raidallisessa pyjamassa',
        title_fi: '',
    },
    { author: '', published: 0, read: true, title_en: 'the great gatsby', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'eläinten vallankumous', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'kirjoituksia kellarista', title_fi: '' },
    {
        author: '',
        published: 0,
        read: true,
        title_en: 'kafkan novellit (muodonmuutos, rangaistussiirtolassa, …)',
        title_fi: '',
    },
    { author: '', published: 0, read: true, title_en: 'asaselin salaliitto', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'idiootti', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'raamattu', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'vihan hedelmät', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'ylpeys & ennakkoluuko', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'bel-ami: kaunis ystävä', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'kasakat', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'david copperfield', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'hiiriä ja ihmisiä', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'pianisti', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'riivaajat', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'sinuhe', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'amerikka / mies joka katosi', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'viisasteleva sydän', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'don quijote', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'ronja ryövärintytär', title_fi: '' },
    { author: '', published: 0, read: true, title_en: 'veljeni leijonamieli', title_fi: '' },
    {
        author: '',
        published: 0,
        read: true,
        title_en: 'nicholas nicklebyn elämä ja seikkailut',
        title_fi: '',
    },
    { author: '', published: 0, read: true, title_en: 'sadan vuoden yksinäisyys', title_fi: '' },

    { author: '', published: 0, read: false, title_en: 'punainen neilikka', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'ivanhoe', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'middlemarch', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'hamlet', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'humiseva harju', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'sivullinen', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'uljas uusi maailma', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'järki ja tunteet', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'kapteenin tytär', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'aikamme sankari', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'isät ja pojat', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'pikku naisia', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'kolea talo (bleak house)', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'kaksi kaupunkia', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'loistava tulevaisuus', title_fi: '' },
    { author: '', published: 0, read: false, title_en: 'our mutual friend', title_fi: '' },
];
